# Generated by Django 3.2.16 on 2022-11-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
        migrations.AddField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(to='base.Tag'),
        ),
    ]
