# Generated by Django 3.2.16 on 2022-12-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_content_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('shared', 'Shared'), ('private', 'Private')], default='public', max_length=7),
        ),
    ]
