# Generated by Django 3.2.16 on 2022-12-25 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_auto_20221224_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(related_name='has_liked_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
