# Generated by Django 3.2.16 on 2022-12-26 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_content_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='has_liked_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(blank=True, to='base.Tag'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='its_messages', to='base.content'),
        ),
    ]
